// vue/src/views/flickering/Example6.vue
<template>
  <p v-if="loading">Loading…</p>
  <div v-else>
    <h2>Flickering Element &gt; Example 5</h2>
    <p>
      Count:
      <span data-cy="count">{{ count }}</span>
    </p>
    <button @click="increment" data-cy="increment">
      Increment
    </button>
  </div>
</template>

<script>
export default {
  name: 'Example6',
  data() {
    return {
      loading: true,
      count: null,
    };
  },
  mounted() {
    setTimeout(() => {
      this.loading = false;
      this.count = 27;
    }, 1000);
  },
  methods: {
    increment() {
      this.count += 1;
    },
  },
};
</script>

// react/src/flickering/example6/index.js
import React, {useState, useEffect} from 'react';

export default function Example6() {
  const [loading, setLoading] = useState(true);
  const [count, setCount] = useState(null);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
      setCount(10);
    }, 1000);
  }, []);

  const increment = () => {
    setCount(count + 1);
  };

  if (loading) {
    return <p>Loading…</p>;
  }

  return (
    <>
      <h2>Flickering Element &gt; Example 6</h2>
      <p>
        Count: <span data-cy="count">{count}</span>
      </p>
      <button onClick={increment} data-cy="increment">
        Increment
      </button>
    </>
  );
}
