// react/src/unprepared/example1/index.js
import React, {useState, useEffect} from 'react';

export default function Example1() {
  const [count, setCount] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    setTimeout(() => {
      setCount(10);
    }, 1000);
  }, []);

  const increment = () => {
    if (count === null) {
      setError('Tried to increment count before it was set!');
    } else {
      setCount(count + 1);
    }
  };

  return (
    <>
      <h2>Unprepared Element &gt; Example 1</h2>
      {error && <p>{error}</p>}
      <p>
        {count === null ? (
          'Loading count…'
        ) : (
          <>
            Count: <span data-cy="count">{count}</span>
          </>
        )}
      </p>
      <button onClick={increment} data-cy="increment">
        Increment
      </button>
    </>
  );
}

// vue/src/views/Example1.vue
<template>
  <div>
    <h2>Unprepared Element &gt; Example 1</h2>
    <p v-if="error">{{ error }}</p>

    <p v-if="count === null">
      Loading count…
    </p>
    <p v-else>
      Count:
      <span data-cy="count">{{ count }}</span>
    </p>
    <button @click="increment" data-cy="increment">
      Increment
    </button>
  </div>
</template>

<script>
export default {
  name: 'Example1',
  data() {
    return {
      count: null,
      error: null,
    };
  },
  mounted() {
    setTimeout(() => {
      this.count = 27;
    }, 1000);
  },
  methods: {
    increment() {
      if (this.count === null) {
        this.error = 'Tried to increment count before it was set!';
      } else {
        this.count += 1;
      }
    },
  },
};
</script>
