// react/src/unprepared/example4/index.js
import React, {useEffect} from 'react';
import {useSelector, useDispatch} from 'react-redux';
import {loadCountFromServer, increment} from './store/actions';

export default function Example4() {
  const dispatch = useDispatch();
  const count = useSelector(state => state.example4);

  useEffect(() => {
    dispatch(loadCountFromServer);
  }, [dispatch]);

  const handleIncrement = () => {
    dispatch(increment());
  };

  if (count === null) {
    return <p>Loading…</p>;
  }

  return (
    <>
      <h2>Example 1</h2>
      <p>
        {count === null ? (
          'Loading count…'
        ) : (
          <>
            Count: <span data-cy="count">{count}</span>
          </>
        )}
      </p>
      <button
        onClick={handleIncrement}
        data-cy="increment"
        disabled={count === null}
      >
        Increment
      </button>
    </>
  );
}

// vue/src/views/Example4.vue
<template>
  <div>
    <h2>Unprepared Element &gt; Example 4</h2>
    <p v-if="error">{{ error }}</p>

    <p v-if="count === null">
      Loading count…
    </p>
    <p v-else>
      Count:
      <span data-cy="count">{{ count }}</span>
    </p>
    <button @click="increment" :disabled="count === null" data-cy="increment">
      Increment
    </button>
  </div>
</template>

<script>
import {mapState, mapActions, mapMutations} from 'vuex';

export default {
  name: 'Example4',
  mounted() {
    this.loadCountFromServer();
  },
  data() {
    return {
      error: null,
    };
  },
  methods: {
    ...mapActions({
      loadCountFromServer: 'example4/loadCountFromServer',
    }),
    ...mapMutations({
      increment: 'example4/increment',
    }),
    handleIncrement() {
      if (this.count === null) {
        this.error = 'Tried to increment count before it was set!';
      } else {
        this.increment();
      }
    },
  },
  computed: mapState({
    count: state => state.example4.count,
  }),
};
</script>
