// react/src/unprepared/example2/index.js
import React, {useState, useEffect} from 'react';

export default function Example2() {
  const [count, setCount] = useState(null);

  useEffect(() => {
    setTimeout(() => {
      setCount(10);
    }, 1000);
  }, []);

  const increment = () => {
    setCount(count + 1);
  };

  return (
    <>
      <h2>Unprepared Element &gt; Example 2</h2>
      <p>
        {count === null ? (
          'Loading count…'
        ) : (
          <>
            Count: <span data-cy="count">{count}</span>
          </>
        )}
      </p>
      <button onClick={increment} data-cy="increment" disabled={count === null}>
        Increment
      </button>
    </>
  );
}

// vue/src/views/unprepared/Example2.vue
<template>
  <div>
    <h2>Unprepared Element &gt; Example 2</h2>
    <p v-if="error">{{ error }}</p>

    <p v-if="count === null">
      Loading count…
    </p>
    <p v-else>
      Count:
      <span data-cy="count">{{ count }}</span>
    </p>
    <button @click="increment" :disabled="count === null" data-cy="increment">
      Increment
    </button>
  </div>
</template>

<script>
export default {
  name: 'Example2',
  data() {
    return {
      count: null,
      error: null,
    };
  },
  mounted() {
    setTimeout(() => {
      this.count = 27;
    }, 1000);
  },
  methods: {
    increment() {
      if (this.count === null) {
        this.error = 'Tried to increment count before it was set!';
      } else {
        this.count += 1;
      }
    },
  },
};
</script>
